version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: instructai-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass yourredispassword
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=yourredispassword

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379:0:yourredispassword
    ports:
      - "8081:8081"
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data: