services:
  - type: web
    name: interview-feedback-service
    env: docker
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      # Database Configuration
      - key: DATABASE_URL
        fromDatabase:
          name: instructai-db
          property: connectionString
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      
      # JPA/Hibernate Configuration
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        value: false
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION
        value: true
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_BOOT_ALLOW_JDBC_METADATA_ACCESS
        value: false
      
      # Socket.IO Configuration
      - key: SOCKETIO_HOST
        value: 0.0.0.0
      - key: SOCKETIO_PORT
        value: 9092
      
      # Redis Configuration
      - key: SPRING_REDIS_HOST
        fromService:
          type: redis
          name: instructai-redis
          property: host
      - key: SPRING_REDIS_PORT
        fromService:
          type: redis
          name: instructai-redis
          property: port
      - key: SPRING_REDIS_PASSWORD
        fromService:
          type: redis
          name: instructai-redis
          property: password
      - key: SPRING_REDIS_DATABASE
        value: 0
      
      # Application Configuration
      - key: SPRING_JACKSON_SERIALIZATION_FAIL_ON_EMPTY_BEANS
        value: false
      - key: SPRING_JACKSON_SERIALIZATION_WRITE_DATES_AS_TIMESTAMPS
        value: false
      - key: FRONTEND_CLIENT
        value: https://instruct-ai-oher.vercel.app
      
      # Security Configuration
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: 86400000
      - key: SPRING_SECURITY_USER_NAME
        value: admin
      - key: SPRING_SECURITY_USER_PASSWORD
        generateValue: true
      
      # API Keys
      - key: GEMINI_API_KEY
        value: AIzaSyAsyukBPOYO39DgAyFiHIS_0up_KC8eJaY
    
    buildFilter:
      paths:
        - server/**

databases:
  - name: instructai-db
    databaseName: instruct_ai
    user: instruct_ai_user
    plan: free

  - name: instructai-redis
    type: redis
    plan: free